spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  application:
    name: feign-test
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://35.220.159.226:3306/picInfo
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8667
